controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    diff_drive_controller:
      type: diff_drive_controller/DiffDriveController

joint_state_broadcaster:
  ros__parameters:
    use_sim_time: true

diff_drive_controller:
  ros__parameters:
    use_sim_time: true
    
    # joints
    left_wheel_names:  ["left_wheel_joint"]
    right_wheel_names: ["right_wheel_joint"]

    # geometry
    wheel_separation: 0.35
    wheel_radius: 0.05

    # frames & behavior
    odom_frame_id: odom
    base_frame_id: base_link
    enable_odom_tf: true
    publish_rate: 50.0
    cmd_vel_timeout: 0.5
    
    # CRITICAL: Add these parameters
    use_stamped_vel: false
    velocity_rolling_window_size: 10
    publish_wheel_data: true
    publish_odom: true
    open_loop: false
    publish_limited_velocity: true